const heads = [
  "effect", "thought",
  "bag", "craft", "line", "plane", "port", "tight",
  "fish",
  "chair", "hole", "pit",
  "head",
  "work",
  "struck",
  "ache", "bone", "drop", "ground", "hand", "hoe", "log", "pack", "space", "stabbing", "stroke", "water", "woods", "yard",
  "lands",
  "pipes",
  "player", "room",
  "code", "storm", "yard",
  "ball",
  "mat", "robe", "room", "tub", "water",
  "axe", "cruiser", "cry", "ship",
  "comber",
  "curd",
  "rock", "room", "spread", "time",
  "hive", "keeper", "keeping", "wax",
  "hand",
  "ache",
  "board",
  "board",
  "pox", "soup",
  "hood", "proof", "ren",
  "ware", "strap",
  "yard",
  "effect",
  "flower", "hop",
  "ache",
  "board",
  "board",
  "berry", "bird", "board", "out",
  "buster",
  "bells", "berry", "bird", "bonnets",
  "cat", "tail",
  "guard",
  "binder", "case", "keeper", "mark", "mobile", "shelf", "worm",
  "strap", "leg", "lace", "s",
  "tie", "string", "man",
  "car", "stick",
  "storm", "scape", "cover",
  "room", "rack", "stand", "tail",
  "blooded", "hearted", "front", "wave",
  "book", "er", "ing", "ware",
  "bread", "cob", "field", "flakes", "meal",
  "beam", "through", "water", "up",
  "side",
  "cat", "her", "net", "bowl", "tank",
  "pole", "ship", "staff",
  "board", "ing", "space",
  "bed", "pot", "girl", "ing",
  "ball", "path", "print", "wear", "note", "step", "rest",
  "lift", "ful",
  "hole", "strap",
  "thing",
  "case", "office", "script", "man", "mortem", "graduate",
  "car", "track", "horse",
  "coat", "fall", "storm", "water", "drop", "forest", "proof",
  "bank", "bed", "side", "boat",
  "trip", "side", "block", "way", "work", "map", "house",
  "slide", "star", "bottom",
  "mate", "ful", "service", "divider", "temperature",
  "ladder", "line", "tie",
  "house", "mate", "work", "yard",
  "shore", "side", "water", "bed", "port",
  "ling", "pod", "bank",
  "lace", "maker", "shine", "box", "wear",
  "yard", "wreck", "ment", "builder", "load", "shape",
  "bread", "cake", "stop",
  "walk", "line", "kick", "board", "show", "burns",
  "fish", "ware", "smith",
  "light", "scraper", "lark",
  "ball", "fall", "storm", "man", "flake", "bank", "blower",
  "eye", "cup", "spoon", "bag", "house", "time",
  "brush", "paste", "pick", "ache", "less", "mark",
  "house", "top", "frog", "line",
  "dog", "tower", "watch",
  "fall", "proof", "melon", "way", "shed", "line", "front", "works",
  "chair", "house", "base", "lock",
  "mill", "shield", "storm", "breaker", "fall", "pipe",
  "play", "book", "smith", "search", "wrap",
  "place", "load", "shop", "force", "bench", "flow", "station",
  "wide", "view", "class", "power",
  "hole", "wood",
  "stick", "work", "arm", "age",
  "ster",
  "hour", "gravity",
  "keeper", "plane", "s"
];

export default heads;
