const words = {
  after: ["aftereffect", "afterthought"],
  air: ["airbag", "aircraft", "airline", "airplane", "airport", "airtight"],
  angel: ["angelfish"],
  arm: ["armchair", "armhole", "armpit"],
  arrow: ["arrowhead"],
  art: ["artwork"],
  awe: ["awestruck"],
  back: [
    "backache",
    "backbone",
    "backdrop",
    "background",
    "backhand",
    "backhoe",
    "backlog",
    "backpack",
    "backspace",
    "backstabbing",
    "backstroke",
    "backwater",
    "backwoods",
    "backyard"
  ],
  bad: ["badlands"],
  bag: ["bagpipes"],
  ball: ["ballplayer", "ballroom", "ballpoint", "ballpark", "ballgame", "ballfield", "ballclub", "ballcap"],
  bar: ["barcode", "barnstorm", "barnyard"],
  base: ["baseball"],
  basket: ["basketball"],
  bath: ["bathmat", "bathrobe", "bathroom", "bathtub", "bathwater"],
  battle: ["battleaxe", "battlecruiser", "battlecry", "battleship"],
  beach: ["beachcomber"],
  bean: ["beancurd"],
  bed: ["bedrock", "bedroom", "bedspread", "bedtime"],
  bee: ["beehive", "beekeeper", "beekeeping", "beewax"],
  before: ["beforehand"],
  bell: ["bellflower", "bellhop"],
  belly: ["bellyache"],
  benchmark: ["benchmark"],
  bill: ["billboard"],
  birth: ["birthday", "birthplace", "birthrate", "birthright"],
  bitter: ["bitterroot", "bittersweet"],
  black: ["blackberry", "blackbird", "blackboard", "blackout"],
  block: ["blockbuster"],
  blue: ["bluebells", "blueberry", "bluebird", "bluebonnets"],
  bob: ["bobcat", "bobtail"],
  body: ["bodyguard", "bodywash"],
  book: ["bookbinder", "bookcase", "bookkeeper", "bookmark", "bookmobile", "bookshelf", "bookworm", "bookclub"],
  boot: ["bootstrap", "bootleg", "bootlace", "boots"],
  bottle: ["bottleneck", "bottletop", "bottlebrush", "bottlecap", "bottle opener"],
  bow: ["bowtie", "bowstring", "bowman"],
  box: ["boxcar", "boxwood"],
  brain: ["brainstorm", "brainwash"],
  bread: ["breadcrumb", "breadbasket", "breadbox", "breadline", "breadwinner"],
  break: ["breakfast", "breakthrough", "breakwater", "breakup"],
  bright: ["brightside"],
  broom: ["broomstick"],
  brother: ["brotherhood", "brotherinlaw"],
  bull: ["bulldog", "bullfrog", "bullhorn", "bullseye"],
  butter: ["buttercup", "butterfly", "buttermilk", "butterfingers"],
  button: ["buttonhole", "buttonwood"],
  camp: ["campground", "campsite", "campfire", "campus"],
  card: ["cardboard", "cardholder", "cardigan", "cardsharp"],
  carpet: ["carpetbag", "carpeting"],
  cat: ["catfish", "catnap", "catwalk", "cat toy"],
  chain: ["chainlink", "chainsaw", "chainmail"],
  chalk: ["chalkboard", "chalkline"],
  chair: ["chairlift", "chairman", "chairperson", "armchair", "highchair", "wheelchair"],
  chance: ["chancel", "chancery"],
  change: ["changeover", "changeling"],
  check: ["checkbook", "checkmate", "checkpoint", "checkup"],
  chest: ["chestnut", "chestpiece"],
  chicken: ["chickenpox", "chickensoup"],
  child: ["childhood", "childproof", "children"],
  chin: ["chinaware", "chinatown", "chinstrap"],
  church: ["churchyard", "churchgoer", "churchman", "churchwoman"],
  circle: ["circlet", "circling"],
  class: ["classroom", "classmate", "classwork", "classify"],
  clock: ["clockface", "clocktower", "clockwork", "alarmclock"],
  cloud: ["cloudburst", "cloudscape", "cloudcover", "cloudiness"],
  coat: ["coatroom", "coatrack", "coatstand", "coattail"],
  cold: ["coldblooded", "coldhearted", "coldfront", "coldwave"],
  cook: ["cookbook", "cooker", "cooking", "cookware"],
  corn: ["cornbread", "corncob", "cornfield", "cornflakes", "cornmeal"],
  cross: ["crossbeam", "crossbow", "crosswalk", "crossword", "crossover"],
  day: ["daybreak", "daycare", "daydream", "daylight", "dayschool"],
  dog: ["doghouse", "dogsled", "dogwood", "dogfight", "dogcatcher", "doggie"],
  door: ["doorknob", "doorstep", "doorway", "doormat", "doorbell", "doorframe", "doorstop"],
  dragon: ["dragonfly", "dragonslayer"],
  drop: ["dropout", "dropper"],
  earth: ["earthquake", "earthworm", "earthbound", "earthwork", "earthrise", "earthtone"],
  egg: ["egghead", "eggnog", "eggshell", "eggplant"],
  eye: ["eyeball", "eyebrow", "eyelash", "eyewear", "eyelid", "eyepiece", "eyesight", "eyesore"],
  face: ["facelift", "facetime", "facebook", "facemask"],
  farm: ["farmhouse", "farmland", "farmyard", "farmer"],
  fire: ["fireball", "fireplace", "fireproof", "firefighter", "firehouse", "firestorm", "firewood", "firearm"],
  fish: ["fishhook", "fishing", "fishnet", "fishbowl", "fishtank"],
  flag: ["flagpole", "flagship", "flagstaff"],
  floor: ["floorboard", "flooring", "floorspace"],
  flower: ["flowerbed", "flowerpot", "flowergirl", "flowering"],
  foot: ["football", "footpath", "footprint", "footwear", "footnote", "footstep", "footrest"],
  fork: ["forklift", "forkful"],
  fox: ["foxhole", "foxtrot"],
  free: ["freelance", "freehold"],
  friend: ["friendship", "friendly"],
  garden: ["gardenia", "gardening", "gardenpath", "gardenia"],
  gate: ["gatepost", "gateway", "gateskeeper"],
  gold: ["goldfish", "goldmine", "goldsmith", "goldrush", "goldleaf", "goldplated"],
  grass: ["grasshopper", "grassland", "grassroots"],
  hand: ["handbag", "handbook", "handmade", "handshake", "handwriting", "handrail", "handcuff", "handgun", "handheld", "handwork"],
  head: ["headache", "headband", "headphones", "headlight", "headboard", "headcount", "headstart"],
  heart: ["heartbeat", "heartbreak", "heartsick", "heartthrob"],
  hill: ["hilltop", "hillside", "hillock", "hillbilly"],
  home: ["homework", "homegrown", "homeroom", "homeowner", "homestead"],
  horse: ["horseback", "horsefly", "horsehair", "horseshoe", "horsemanship"],
  house: ["houseboat", "housecall", "housesit", "housemaid", "houseplant", "houseparty", "houseguest", "housework", "household", "housekeeper", "housewarming", "housebroken", "housecleaning"],
  ice: ["iceberg", "icebox", "icecream", "icelake", "iceskate", "icicle"],
  iron: ["ironsmith", "ironing", "ironwork"],
  jelly: ["jellybean", "jellyfish"],
  key: ["keyboard", "keyhole", "keychain", "keystone", "keypad", "keynote", "keyring"],
  king: ["kingdom", "kingpin", "kingship"],
  land: ["landscape", "landmark", "landowner", "landfill", "landslide"],
  lamp: ["lamppost", "lamplight", "lampshade"],
  leaf: ["leaflet", "leafpile", "leafmold"],
  leg: ["legroom", "legwork", "legume", "legless"],
  letter: ["letterhead", "letterman", "letterbox", "lettering"],
  light: ["lightbulb", "lighthouse", "lightweight", "lightswitch", "lightyear", "lightbeam", "lightproof"],
  line: ["headline", "lifeline", "pipeline", "baseline", "deadline", "guideline"],
  lip: ["lipstick", "lipread", "lipgloss"],
  man: ["manhole", "manpower", "mankind", "manservant", "manhunt", "mansion", "manmade"],
  market: ["marketplace", "marketshare", "marketvalue", "marketwatch", "marketprice", "markettrend"],
  match: ["matchbox", "matchstick"],
  mind: ["mindset", "mindscape", "mindless", "mindful"],
  milk: ["milkshake", "milkmaid", "milkman", "milksop"],
  moon: ["moonlight", "moonbeam", "moonrise", "moonset"],
  morning: ["morningstar", "morningglory"],
  mother: ["motherhood", "motherland", "motherload", "motherly"],
  mouth: ["mouthful", "mouthpiece", "mouthwash"],
  move: ["movement", "mover", "movietime"],
  night: ["nightfall", "nightlife", "nightclub", "nighttime", "nightgown"],
  nose: ["nosebleed", "nosedive", "nosebag"],
  ocean: ["oceanfront", "oceanside", "oceanwave"],
  office: ["officeholder", "officework", "officemate"],
  orange: ["orangutan"],
  paper: ["paperback", "paperclip", "paperwork", "papermill"],
  part: ["parttime", "partwork", "partowner", "partisan"],
  pass: ["passcode", "passage", "password"],
  pen: ["penholder", "penknife", "pencilcase", "pennant"],
  pit: ["pitfall", "pitbull"],
  place: ["placemat", "placement", "placemark", "placeholder"],
  plant: ["plantation", "plantlife", "plantwork"],
  play: ["playground", "playhouse", "playbook", "playtime", "playback", "playmaker", "plaything"],
  post: ["postcard", "postoffice", "postscript", "postman", "postmortem", "postgraduate", "postdate", "postmark", "postman", "postmen"],
  race: ["racecar", "racetrack", "racehorse"],
  rain: ["raincoat", "rainfall", "rainstorm", "rainwater", "raindrop", "rainforest", "rainproof", "rainbow", "raincheck", "raincloud", "rain jacket"],
  river: ["riverbank", "riverbed", "riverside", "riverboat"],
  road: ["roadtrip", "roadside", "roadblock", "roadway", "roadwork", "roadmap", "roadhouse"],
  rock: ["rockslide", "rockstar", "rockbottom"],
  room: ["roommate", "roomful", "roomservice", "roomette", "roomdivider", "roomtemperature"],
  rope: ["ropeladder", "ropeline", "ropetie"],
  school: ["schoolhouse", "schoolmate", "schoolwork", "schoolyard"],
  sea: ["seashore", "seaside", "seawater", "seabed", "seaport"],
  seed: ["seedling", "seedpod", "seedbank"],
  shoe: ["shoelace", "shoemaker", "shoeshine", "shoebox", "shoewear"],
  ship: ["shipyard", "shipwreck", "shipment", "shipbuilder", "shipload", "shipshape"],
  short: ["shortbread", "shortcake", "shortstop"],
  side: ["sidewalk", "sideline", "sidekick", "sideboard", "sideshow", "sideburns"],
  silver: ["silverfish", "silverware", "silversmith"],  
  sky: ["skylight", "skyscraper", "skylark"],
  snow: ["snowball", "snowfall", "snowstorm", "snowman", "snowflake", "snowbank", "snowblower"],
  sock: ["sockeye", "sockpuppet", "socks", "sockless", "sock drawer"],
  soft: ["software", "softball"],
  star: ["starlight", "starfish", "starboard", "stargaze"],
  stone: ["stonewall", "stonework", "stonecrop", "stoneware"],
  struck: ["struckout", "struckdown", "struckoff", "struckup", "struckthrough", "struckaside"],
  sun: ["sunlight", "sunburn", "sunglasses", "sunrise", "sunset", "sunshine", "sunflower", "sunscreen", "sunroof"],
  table: ["tablecloth", "tablespoon", "tableware", "tabletop", "tablesaw", "tableland"],
  tail: ["tailbone", "tailor", "tailwind"],
  tea: ["teapot", "teacup", "teaspoon", "teabag", "teahouse", "teatime"],
  tooth: ["toothbrush", "toothpaste", "toothpick", "toothache", "toothless", "toothmark"],
  tree: ["treehouse", "treetop", "treefrog", "treeline"],
  wash: ["washboard", "washbasin", "washcloth", "washout", "washup"],
  watch: ["watchdog", "watchtower", "wristwatch"],
  water: ["waterfall", "waterproof", "watermelon", "waterway", "watershed", "waterline", "waterfront", "waterworks"],
  ware: ["warehouse"],
  wheel: ["wheelchair", "wheelhouse", "wheelbase", "wheellock"],
  wind: ["windmill", "windshield", "windstorm", "windbreaker", "windfall", "windpipe"],
  word: ["wordplay", "wordbook", "wordsmith", "wordsearch", "wordwrap"],
  work: ["workplace", "workload", "workshop", "workforce", "workbench", "workflow", "workstation"],
  world: ["worldwide", "worldview", "worldclass", "worldliness", "worldpower"],
  worm: ["wormhole", "wormwood"],
  yard: ["yardstick", "yardwork", "yardarm", "yardage"],
  young: ["youngster", "youngblood"],
  zero: ["zerohour", "zerogravity"],
  zoo: ["zookeeper", "zooplane"]
};

export default words;
